paths:
  /review/{memberId}:
    get:
      tags:
        - Review
      summary: Get reviews by member ID
      parameters:
        - name: memberId
          in: path
          required: true
          type: integer
          description: ID of the member to retrieve reviews for
        - name: page
          in: query
          required: false
          type: integer
          description: Page number for pagination
        - name: offset
          in: query
          required: false
          type: integer
          description: Offset for pagination
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: success!
              result:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    member_name:
                      type: string
                      example: swagger
                    store_name:
                      type: string
                      example: store_test
                    body:
                      type: string
                      example: good good
                    score:
                      type: integer
                      example: 5

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /review/storeId/{storeId}:
    get:
      tags:
        - Review
      summary: Get reviews by store ID with pagination
      parameters:
        - name: storeId
          in: path
          required: true
          type: integer
          description: ID of the store to retrieve reviews for
        - name: lastId
          in: query
          required: false
          type: integer
          description: ID of the last review fetched (for cursor based pagination)
        - name: page
          in: query
          required: false
          type: integer
          description: Page number for traditional offset based pagination
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: success!
              result:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    member_name:
                      type: string
                      example: swagger
                    store_name:
                      type: string
                      example: store_test
                    body:
                      type: string
                      example: good good
                    score:
                      type: integer
                      example: 5

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /mission/{missionId}:
    get:
      tags:
        - Mission
      summary: Retrieve ongoing missions by mission ID
      parameters:
        - name: missionId
          in: path
          required: true
          type: integer
          description: ID of the mission to retrieve ongoing missions for
        - name: page
          in: query
          required: false
          type: integer
          description: Page number for pagination
        - name: offset
          in: query
          required: false
          type: integer
          description: Offset for pagination
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: success!
              result:
                type: array
                items:
                  type: object
                  properties:
                    member_mission_id:
                      type: integer
                      example: 1
                    status:
                      type: string
                      example: INPROGRESS
                    store_name:
                      type: string
                      example: store_test
                    reward:
                      type: integer
                      example: 200
                    deadline:
                      type: string
                      format: date-time
                      example: "2024-08-02T15:00:00.000Z"
                    mission_spec:
                      type: string
                      example: pay more than 30000

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
